// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myufvzhdsmehhpkfwdzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dWZ2emhkc21laGhwa2Z3ZHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MDg4MjQsImV4cCI6MjA2OTM4NDgyNH0.L6nUT4nz2iJ4oVr1KBjLzyuFeCi0X4_3YgfyvRiu5ww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});